version: "3.9"
services:
  web-app-db:
    image: mysql
    container_name: wordle-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordle
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web-app:
    build: .
    container_name: wordle-web-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      web-app-db:
          condition: service_healthy
  wordle-front:
    build: ./web
    container_name: wordle-web-front
    ports:
      - "3000:3000"
    depends_on:
        - web-app
#  telegram-bot:
#    image: wordle-telegram-bot
#    container_name: wordle-telegram-bot



