version: "3.9"
services:
  # web-app-db:
  #   image: mysql
  #   container_name: wordle-db
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #   ports:
  #      - "3306:3306"
    # healthcheck:
    #    test: mysql ${MYSQL_DATABASE} --user=root --password='${MYSQL_ROOT_PASSWORD}' --silent --execute "SELECT 1;"
    #    timeout: 20s
    #    retries: 10
  web-app:
    build: .
    image: tacswordleregistry1.azurecr.io/wordle-web-app
    container_name: wordle-web-app
    domainname: "tacs-wordle-web1"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - web-app-db
  wordle-front:
    build: ./web
    image: tacswordleregistry1.azurecr.io/wordle-web-front
    container_name: wordle-web-front
    ports:
      - "3000:3000"
    depends_on:
      - web-app
#  telegram-bot:
#    image: wordle-telegram-bot
#    container_name: wordle-telegram-bot



